fix compile error (sparta compiler warns it) MessagePayloadPlainText.cs(9,29): error CS0840: `SocialPoint.Social.MessagePayloadPlainText.Text.get' must have a body because it is not marked abstract or extern. The property can be automatically implemented when you define both accessors.